[geral]
;  Se não passar nenhuma ação, vai para a index
default_m=nfse
default_u=main
default_a=Nfse
default_acao=indexAction

; Saída default para respostas de requisições do módulo
WS_SAIDA_PADRAO=JSON
WS_SAIDAS_PERMITIDAS[]=JSON
WS_SAIDAS_PERMITIDAS[]=XML

; URL de acesso ao webservice
urlSefinProducao=https://sefin.nfse.gov.br/SefinNacional/nfse
urlSefinHomologacao=https://sefin.producaorestrita.nfse.gov.br/SefinNacional/nfse
urlAdnProducao=https://adn.nfse.gov.br/danfse
urlAdnHomologacao=https://adn.producaorestrita.nfse.gov.br/danfse

; Ambiente de acesso ao webservice: 1=Produção | 2=Homologação
ambiente=1

; Versão do layout da NFS-e
versao=1.01

; Nomes e senhas dos certificados digitais A1
nome_certificado-emedaux=EMEDAUX.pfx
senha_certificado-emedaux=1234

; Inscricao Federal - Autorização para Emissão de Documentos Fiscais Eletrônicos
cnpj-emedaux="83.050.245/0001-50"

; idCNAE - Código reduzido de quatro dígitos, que no processamento da NFPS-e retorna o código e descrição original
idCNAE-emedaux=250401

; im - Inscrição Municipal da empresa
im-emedaux=0885258

; Codigo do município para emissão da NFS-e
codigo_municipio-emedaux=4205407